import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import Sidebar from "./components/sidebar/sidebar";
import Navbar from "./components/navbar/navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <div className="flex min-h-screen bg-black">
            <Sidebar />
            <div className="flex flex-col w-full">
              <Navbar />
              <div className="flex-grow">{children}</div>
            </div>
          </div>
        </Providers>
        <script src="https://cdn.plot.ly/plotly-latest.min.js" />
      </body>
    </html>
  );
}
